services:
  mongodb:
    image: mongo:latest
    container_name: Api-contactos
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: contactos
      MONGO_INITDB_ROOT_PASSWORD: contactos1234
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
